# Contributor License Agreement
# This file documents the CLA for Unbitrium

name: Unbitrium Contributor License Agreement

description: >
  By contributing to Unbitrium, you agree that your contributions
  will be licensed under the EUPL-1.2 License.

version: 1.0.0

contributor:
  agreement: |
    ## Contributor License Agreement

    Thank you for your interest in contributing to Unbitrium ("Project"),
    maintained by Olaf Yunus Laitinen Imanov ("Maintainer").

    By submitting a contribution (including any pull request, documentation
    change, or other material) to this Project, you agree to the following:

    ### 1. Licensing
    You agree that your contributions will be licensed under the
    European Union Public Licence 1.2 (EUPL-1.2) as specified in the
    LICENSE file of this repository.

    ### 2. Ownership
    You represent that you have the right to grant this license for
    your contributions. If your employer has rights to intellectual
    property that you create, you have received permission to make
    the contribution on behalf of that employer.

    ### 3. Original Work
    You represent that your contributions are your original creation
    or that you have the appropriate licenses and permissions to
    contribute the code.

    ### 4. No Warranty
    You provide your contributions on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

    ### 5. Notification
    You agree to notify the Maintainer of any facts or circumstances
    of which you become aware that would make these representations
    inaccurate in any respect.

sign_cla:
  method: pull_request
  comment: |
    Thank you for your contribution to Unbitrium!

    By submitting this pull request, you agree to the
    [Contributor License Agreement](CLA.yml).

contact:
  email: oyli@dtu.dk
  name: Olaf Yunus Laitinen Imanov
