# Label Configuration for GitHub Issues and Pull Requests
# Apply using: https://github.com/marketplace/actions/github-labeler

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: "Needs immediate attention"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# Type Labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: enhancement"
  color: "84b6eb"
  description: "Improvement to existing functionality"

- name: "type: documentation"
  color: "0075ca"
  description: "Documentation improvements"

- name: "type: question"
  color: "d876e3"
  description: "Further information is requested"

- name: "type: discussion"
  color: "cc317c"
  description: "Discussion topic"

# Status Labels
- name: "status: triage"
  color: "ededed"
  description: "Needs triage"

- name: "status: in-progress"
  color: "0052cc"
  description: "Currently being worked on"

- name: "status: review-needed"
  color: "fbca04"
  description: "Needs review"

- name: "status: blocked"
  color: "b60205"
  description: "Blocked by external dependencies"

- name: "status: stale"
  color: "ffffff"
  description: "No recent activity"

# Component Labels
- name: "component: aggregators"
  color: "c5def5"
  description: "Related to aggregation algorithms"

- name: "component: partitioning"
  color: "c5def5"
  description: "Related to data partitioning"

- name: "component: metrics"
  color: "c5def5"
  description: "Related to heterogeneity metrics"

- name: "component: privacy"
  color: "c5def5"
  description: "Related to privacy mechanisms"

- name: "component: core"
  color: "c5def5"
  description: "Related to core infrastructure"

- name: "component: simulation"
  color: "c5def5"
  description: "Related to simulation engine"

- name: "component: benchmarks"
  color: "c5def5"
  description: "Related to benchmarking"

# Effort Labels
- name: "effort: small"
  color: "bfd4f2"
  description: "Less than 1 hour"

- name: "effort: medium"
  color: "bfd4f2"
  description: "1-4 hours"

- name: "effort: large"
  color: "bfd4f2"
  description: "More than 4 hours"

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or PR already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "breaking-change"
  color: "b60205"
  description: "Introduces breaking changes"

- name: "dependencies"
  color: "0366d6"
  description: "Related to dependencies"

- name: "security"
  color: "b60205"
  description: "Security related"

- name: "performance"
  color: "f9d0c4"
  description: "Performance related"
