---
name: Bug Report
description: Report a bug or unexpected behavior in Unbitrium
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug. Please fill out the form below as completely as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and the bug is not explained there
          required: true
        - label: I am using the latest version of Unbitrium
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Import '...'
        2. Call function '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear description of expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear description of actual behavior
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Provide a minimal code snippet that reproduces the issue
      render: python
      placeholder: |
        from unbitrium import ...

        # Your code here
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Error Traceback
      description: Full error traceback if applicable
      render: shell
      placeholder: Paste the complete error traceback

  - type: input
    id: unbitrium-version
    attributes:
      label: Unbitrium Version
      description: Output of `python -c "import unbitrium; print(unbitrium.__version__)"`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "Python 3.12.0"
    validations:
      required: true

  - type: input
    id: torch-version
    attributes:
      label: PyTorch Version
      description: Output of `python -c "import torch; print(torch.__version__)"`
      placeholder: "2.4.0"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Ubuntu/Debian
        - Windows 10/11
        - macOS
        - Other Linux
        - Other
    validations:
      required: true

  - type: checkboxes
    id: gpu
    attributes:
      label: GPU Configuration
      options:
        - label: Using GPU (CUDA)
        - label: Using Apple Silicon (MPS)
        - label: CPU only

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, logs, etc.
